<?php

    return [
        '/' => 'controllers/home.php',
        '/inicio-sesion' => 'controllers/Session/inicio-sesion.php',
        '/registro-ceo' => 'controllers/Registro/registro-ceo.php',
        '/empresa' => 'controllers/Empresa/empresa.php',
        '/existe-empresa' => 'controllers/Empresa/existe-empresa.php',
        '/eliminar-empresa' => 'controllers/Empresa/eliminar-empresa.php',
        '/buscar-empleados' => 'controllers/Empresa/buscar-empleados.php',
        '/departamentos' => 'controllers/Departamento/departamentos.php',
        '/departamento' => 'controllers/Departamento/departamento.php',
        '/crear-departamento' => 'controllers/Departamento/crear-departamento.php',
        '/plantillaCSV' => 'controllers/Departamento/plantillaCSV.php',
        '/eliminar-departamento' => 'controllers/Departamento/eliminar-departamento.php',
        '/empleado' => 'controllers/Empleado/empleado.php',
        '/existe-empleado' => 'controllers/Empleado/existe-empleado.php',
        '/eliminar-empleado' => 'controllers/Empleado/eliminar-empleado.php',
        '/mi-cuenta' => 'controllers/Session/mi-cuenta.php',
        '/cambiar-contrasena' => 'controllers/Session/cambiar-contrasena.php',
        '/comprobar-correo' => 'controllers/Session/comprobar-correo.php',
        '/nueva-contra' => 'controllers/Session/nueva-contra.php',
        '/delegar-usuarios' => 'controllers/Session/delegar-usuarios.php',
        '/cambiar-rol' => 'controllers/Session/cambiar-rol.php',
        '/notificaciones' => 'controllers/Session/notificaciones.php',
        '/cerrar-sesion' => 'controllers/Session/cerrar-sesion.php',
        '/calcular-nomina/empleado' => 'controllers/Nomina/calcular-nomina.php',
        '/historial-nomina/empleado' => 'controllers/Nomina/historial-nomina.php',
        '/nomina/empleado' => 'controllers/Nomina/nomina.php',
        '/estadisticas' => 'controllers/estadisticas.php',
        '/costes-empleado' => 'controllers/Empleado/costes-empleado.php',
        '/costes-empleado-mes' => 'controllers/Empleado/costes-empleado-mes.php',
        '/costes-totales-departamento' => 'controllers/Departamento/costes-totales-departamento.php',
        '/calcular-finiquito/empleado' => 'controllers/Finiquito/calcular-finiquito.php',
        '/finiquito/empleado' => 'controllers/Finiquito/finiquito.php',

        '/usuario-empleado' => 'controllers/UsuarioEmpleado/usuario-empleado.php',
        '/usuario-empleado/historial-nomina/empleado' => 'controllers/UsuarioEmpleado/historial-nomina.php',
        '/calendario-empleado/empleado' => 'controllers/UsuarioEmpleado/calendario-empleado.php',
        '/solicitar-dias-vacaciones' => 'controllers/UsuarioEmpleado/solicitar-dias-vacaciones.php',
        '/calendario-empleado-eventos' => 'controllers/UsuarioEmpleado/calendario-empleado-eventos.php',

        '/politica-privacidad' => 'controllers/PagEstaticas/politica-privacidad.php',
        '/cookies' => 'controllers/PagEstaticas/cookies.php',
        '/sobre-nosotros' => 'controllers/PagEstaticas/sobre-nosotros.php',
        '/contacto' => 'controllers/PagEstaticas/contacto.php',
    ];